name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: PetroRavlinko-CV.tex
      - name: Upload PDF file
        run: mkdir -p target
        run: mv PetroRavlinko-CV.pdf target/PetroRavlinko-CV.pdf
        uses: actions/upload-artifact@master
        with:
          name: cv.zip
          path: ./target  
